GET http://localhost:3000/users



###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "user101",
    "password": "123456"
}

###

GET http://localhost:3000/subscribers/618a9836f3f7ac4f6b18b6a0

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Amazing Person",
    "subscribedToChannel": "Web Dev Simplified"
}



###

POST http://localhost:3000/expense/1
Content-Type: application/json
{
    "name": "Amazing Person",
    "subscribedToChannel": "Web Dev Simplified"
}

###
DELETE http://localhost:3000/subscribers/618a9836f3f7ac4f6b18b6a0

###

//Creating expense
POST http://localhost:3000/projects
Content-Type: : application/json

{
    "id": 3,
    "project_id": 2,
    "category_id": 2,
    "name": "test",
    "description": "testing",
    "amount": 2,
    "created_at": ,
    "created_by": "Helen",
    "updated_at": ,
    "updated_by": "Helen"
}